### ISSUE TITLE
Support for multiple tags

### ISSUE THREAD

**Issue by mputters** [OrbitzWorldwide/consul-client#157]
Hello,

Right now with a `CatalogOptions` we can only specify one tag (which is what the Consul API offered anyway, so it made sense), however it is now possible to query for multiple tags at the same time, and some clients for other languages have started implementing it.

For now it can only be done using prepared statements:
- https://github.com/hashicorp/consul/issues/1841
- https://github.com/hashicorp/consul/issues/1781

Any chance this could be added to your library?

Thanks.

**Comment by rickfast** [comment]
It can be added, but I'm on vacation for the next week and won't get to it any time soon. It should be a relatively trivial change if you'd like to make a pull request.

**Comment by rickfast** [comment]
Waiting on https://github.com/square/retrofit/issues/1324 to fix this

**Comment by shaharck** [comment]
FYI this is needed from the newly introduced node-meta filter as well

**Comment by rickfast** [comment]
I have a release candidate out with this change: `0.14.0-RC1`. Try it out

**Comment by shaharck** [comment]
@rickfast that was super fast :) i'll check it out

**Comment by thomas-oo** [comment]
Sorry this is a bit confusing, I'm using 0.15.0 and it's claimed to be fixed in 0.14.0. Multiple tag queries in `CatalogClient.getServices(service, queryOptions)` for example doesn't work and only filters using the first tag. There's an [upstream issue in consul](https://github.com/hashicorp/consul/issues/1781) where multiple tags have not been supported through the parameters.

On a sidenote: Could you explain where the fix you observed was? I'd love multi tag support.

Thanks
