### ISSUE TITLE
ConsulCache stops polling for changes

### ISSUE THREAD

**Issue by sgrimm-sg** [OrbitzWorldwide/consul-client#166]
We're using KVCache on a bunch of our servers and it will sometimes, seemingly at random, stop polling for new updates from Consul. It doesn't seem to correlate to any event I can see, and there isn't a log message when it happens. If we deploy identical code to two hosts at the same time, one of them might hit the problem after a few hours and the other one after a few days, but it's not consistent.

I've modified a local copy of ConsulCache to add some debug logging and will update this issue if/when I discover more detail, but wanted to flag it in case others have seen/solved the same problem.

**Comment by rickfast** [comment]
I have a theory about this. I'll test it this evening and report back. We had a similar issue (which was fixed) with 0.8.x at Orbitz, which used CXF/JAX-RS under the hood. The issue was that if there was any kind of network hiccup, the call would fail with a ConnectException before the failure callback is fired, ending the callback loop.

**Comment by rickfast** [comment]
My theory was wrong. Please let me know if you find any more clues.

**Comment by sgrimm-sg** [comment]
Update on this: When I added my debug logging, I needed to upgrade to version 0.13.0 of the client to get the non-shaded classes so I could override them with my modified ones. And the problem hasn't happened since. My guess is it was a manifestation of #161 and was fixed by the fix for that bug. Closing this for now but will comment again if I see it happening again.
