### ISSUE TITLE
register interface do not have address field

### ISSUE THREAD

**Issue by kongchen** [OrbitzWorldwide/consul-client#28]
Hi there,

I'm curious about the register api, according to https://www.consul.io/docs/agent/services.html:
> The address field can be used to specify a service-specific IP address. By default, the IP address of the agent is used, and this does not need to be provided. The port field can be used as well to make a service-oriented architecture simpler to configure; this way, the address and port of a service can be discovered.

I start my service at server **A**, and the consul server agent runs on server **B**, and I use the Consul client's to register my service and I noticed the `Address` in request is null. In my understanding the Consul server will use **A**'s ip address but actually it uses **B**'s address as the node's address.
 
I want to have my service address be sent in the register call, so that the Consul UI will show the correct node's info.

**Comment by kongchen** [comment]
Close this issue for misunderstanding Consul's agent.

**Comment by dnance** [comment]
I do not understand why this issue was closed.  I think it should be reopened.  When I use the http agent registration API I can supply a serviceAddress which populates the serviceAddress field.  When I use the Consul-client AgentClient there isn't anyway to register a service with a different serviceAddress than that of the agent it is connected.
