### ISSUE TITLE
Support multiple host/ports for Consul.builder().withHostAndPort() ?

### ISSUE THREAD

**Issue by bitsofinfo** [OrbitzWorldwide/consul-client#98]
Is there any support to specify multiple consul host/ports in a catalog client etc?

**Comment by rickfast** [comment]
No. Best bet is to create multiple clients. Is this so that you can load balance or failover agents?

**Comment by bitsofinfo** [comment]
Yes basically want to register w/ multiple agents or have failover for discovery

**Comment by rickfast** [comment]
I won't have time to get to this in the near term, but I've marked it help wanted. I think this should be relatively easy to implement w/ multiple clients in the near term.

**Comment by odiszapc** [comment]
This feature leads to redesigning of consul-client, because re-connection strategy and pools arrives here. I guess (@rickfast fix me) the main idea of consul-client is to have pure implementation of Consul HTTP API, then consul-client can be engaged into the more feature-riched library, like Zookeeper client is a core of Apache Curator framework.

**Comment by bitsofinfo** [comment]
:(

**Comment by rickfast** [comment]
i can leave it open as help wanted, but based on the other things i'm working on, i really dont think i'm going to get to this. sorry
